name: Compilar APK con Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Obtener el código fuente
      uses: actions/checkout@v4

    - name: Compilar APK con Buildozer Action
      uses: ArtemSdm/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        submodule_update: false

    - name: Guardar el APK como artefacto descargable
      uses: actions/upload-artifact@v4
      with:
        name: app-android
        path: bin/*.apk
