name: Compilar APK con Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el código fuente
      uses: actions/checkout@v4

    - name: Compilar APK con Buildozer Action
      uses: ArtemSydoryk/buildozer-action@v1
      with:
        command: buildozer -v android debug
        subfolder: .

    - name: Guardar el APK como artefacto descargable
      uses: actions/upload-artifact@v4
      with:
        name: app-android
        path: bin/*.apk
